# Generated by Django 5.2.1 on 2026-02-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0002_rename_user_data_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='motivation',
            field=models.JSONField(default=list),
        ),
    ]
