# Generated by Django 5.2.1 on 2026-02-26 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0003_alter_userdata_motivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='motivation_image',
            field=models.ImageField(blank=True, null=True, upload_to='motivation_images/'),
        ),
        migrations.CreateModel(
            name='UserUrges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('urge_level', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
