# Generated by Django 5.2.1 on 2026-03-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0009_socialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='coaching_style',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='motivation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
