# Generated by Django 5.2.1 on 2026-03-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0010_remove_userdata_coaching_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='panic_audio',
            field=models.FileField(blank=True, null=True, upload_to='panic_audio/'),
        ),
    ]
