# Generated by Django 5.2.1 on 2026-07-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0014_userhabits'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='coaching_style',
            field=models.TextField(blank=True, default=''),
        ),
    ]
