# Generated by Django 5.2.1 on 2026-07-28 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0015_userdata_coaching_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='urges',
            name='urge_note',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='urges',
            name='urge_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 28, 18, 47, 53, 503452, tzinfo=datetime.timezone.utc)),
        ),
    ]
