# Generated by Django 5.2.1 on 2026-08-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0019_habitcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='default_urge_screen',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
