# Generated by Django 5.2.1 on 2026-08-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0021_userdata_seen_ai_coach_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_title',
            field=models.CharField(default=''),
        ),
    ]
