# Generated by Django 5.2.1 on 2026-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0022_chatsession_session_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ai_memory',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
