# Generated by Django 5.2.1 on 2026-08-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0023_userdata_ai_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='ai_memory',
            field=models.JSONField(),
        ),
    ]
