# Generated by Django 5.2.1 on 2026-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0025_alter_userdata_ai_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='ai_memory',
        ),
        migrations.AddField(
            model_name='userdata',
            name='memory',
            field=models.JSONField(default=dict),
        ),
    ]
