# Generated by Django 5.2.1 on 2026-08-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0026_remove_userdata_ai_memory_userdata_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='memory',
            new_name='ai_memory',
        ),
    ]
