# Generated by Django 5.2.17 on 2026-08-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0028_userdata_email_verified_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
