# Generated by Django 5.2.17 on 2026-08-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0029_userdata_premium_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
