# Generated by Django 5.2.17 on 2026-08-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0030_userdata_reminder_enabled_userdata_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ai_data_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='ai_data_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
