# Generated by Django 5.2.17 on 2026-08-10 01:30

from django.db import migrations, models


# Every UserData row that already exists as of this migration belongs to a
# user who signed up under the old flow, i.e. already finished (or never had)
# onboarding -- backfill them to True so this new gate doesn't bounce the
# entire existing user base back into the onboarding flow on their next
# refresh. Only rows created after this migration start at the field's own
# False default and must actually finish onboarding to flip it.
def backfill_onboarding_complete(apps, schema_editor):
    UserData = apps.get_model('bingeBuddyAPI', 'UserData')
    UserData.objects.update(onboarding_complete=True)


class Migration(migrations.Migration):

    dependencies = [
        ('bingeBuddyAPI', '0031_userdata_ai_data_consent_userdata_ai_data_consent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_onboarding_complete, migrations.RunPython.noop),
    ]
